## Кривоногов Н.В., PyTorch, практическое задание № 1

In [1]:
import torch

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Создайте случайный FloatTensor размера 3x4x5

import random

a = torch.FloatTensor(torch.rand(size=(3, 4, 5)))

a

tensor([[[0.1038, 0.3492, 0.3572, 0.5351, 0.4527],
         [0.7374, 0.1563, 0.1913, 0.4652, 0.2187],
         [0.8087, 0.0805, 0.9287, 0.9656, 0.6328],
         [0.5272, 0.3346, 0.6601, 0.8568, 0.2961]],

        [[0.8371, 0.0657, 0.4575, 0.0317, 0.2905],
         [0.5073, 0.7560, 0.5851, 0.3349, 0.9008],
         [0.6587, 0.7992, 0.4581, 0.1046, 0.9529],
         [0.4348, 0.2361, 0.2557, 0.3366, 0.7144]],

        [[0.6277, 0.3700, 0.8178, 0.4416, 0.6451],
         [0.2462, 0.3920, 0.3205, 0.6582, 0.4129],
         [0.5895, 0.3991, 0.4692, 0.6363, 0.2457],
         [0.6891, 0.3989, 0.3650, 0.5326, 0.4578]]])

In [3]:
# или просто: 

a = torch.rand(size=(3, 4, 5))

a

# так как torch.Tensor является сокращённым названием для torch.FloatTensor

tensor([[[0.1972, 0.5457, 0.7613, 0.6676, 0.7794],
         [0.7469, 0.2865, 0.0852, 0.2640, 0.9788],
         [0.3667, 0.7600, 0.5041, 0.6331, 0.2284],
         [0.5822, 0.6420, 0.2077, 0.4924, 0.2155]],

        [[0.1688, 0.5299, 0.5419, 0.7053, 0.2416],
         [0.1603, 0.4546, 0.0436, 0.3853, 0.7941],
         [0.0696, 0.9938, 0.3786, 0.4681, 0.9603],
         [0.9450, 0.9634, 0.9423, 0.7281, 0.7269]],

        [[0.1331, 0.7116, 0.4285, 0.5231, 0.2515],
         [0.0420, 0.9553, 0.7107, 0.1367, 0.0306],
         [0.6400, 0.0912, 0.1052, 0.4585, 0.2596],
         [0.6299, 0.2407, 0.9974, 0.5778, 0.8735]]])

In [4]:
# или же: 

a = torch.rand(size=(3, 4, 5)).type(torch.FloatTensor)

a

tensor([[[0.4286, 0.6565, 0.4759, 0.3813, 0.5502],
         [0.7572, 0.0984, 0.8011, 0.7428, 0.0635],
         [0.3300, 0.4038, 0.5858, 0.1781, 0.0102],
         [0.0105, 0.9626, 0.3428, 0.2934, 0.6756]],

        [[0.7161, 0.2888, 0.3386, 0.9910, 0.3363],
         [0.6436, 0.8437, 0.6034, 0.0851, 0.7297],
         [0.1969, 0.4804, 0.0183, 0.6548, 0.1837],
         [0.6108, 0.0511, 0.3483, 0.1821, 0.2394]],

        [[0.3672, 0.1676, 0.0784, 0.4189, 0.7083],
         [0.7531, 0.2743, 0.4686, 0.0677, 0.9966],
         [0.9275, 0.7235, 0.4190, 0.2543, 0.6772],
         [0.3163, 0.2119, 0.0357, 0.5943, 0.8082]]])

In [5]:
# Выведите его форму (shape)

a.shape

torch.Size([3, 4, 5])

In [6]:
# или: 

a.size()

torch.Size([3, 4, 5])

In [7]:
# Приведите его к форме 6 X 10

a.resize(6, 10)

tensor([[0.4286, 0.6565, 0.4759, 0.3813, 0.5502, 0.7572, 0.0984, 0.8011, 0.7428,
         0.0635],
        [0.3300, 0.4038, 0.5858, 0.1781, 0.0102, 0.0105, 0.9626, 0.3428, 0.2934,
         0.6756],
        [0.7161, 0.2888, 0.3386, 0.9910, 0.3363, 0.6436, 0.8437, 0.6034, 0.0851,
         0.7297],
        [0.1969, 0.4804, 0.0183, 0.6548, 0.1837, 0.6108, 0.0511, 0.3483, 0.1821,
         0.2394],
        [0.3672, 0.1676, 0.0784, 0.4189, 0.7083, 0.7531, 0.2743, 0.4686, 0.0677,
         0.9966],
        [0.9275, 0.7235, 0.4190, 0.2543, 0.6772, 0.3163, 0.2119, 0.0357, 0.5943,
         0.8082]])

In [8]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

b = torch.IntTensor([1, 4, 2, 2, 1])

a * b

tensor([[[0.4286, 2.6259, 0.9517, 0.7626, 0.5502],
         [0.7572, 0.3936, 1.6022, 1.4856, 0.0635],
         [0.3300, 1.6152, 1.1716, 0.3562, 0.0102],
         [0.0105, 3.8503, 0.6856, 0.5867, 0.6756]],

        [[0.7161, 1.1551, 0.6771, 1.9820, 0.3363],
         [0.6436, 3.3749, 1.2068, 0.1702, 0.7297],
         [0.1969, 1.9218, 0.0366, 1.3096, 0.1837],
         [0.6108, 0.2044, 0.6967, 0.3642, 0.2394]],

        [[0.3672, 0.6705, 0.1568, 0.8377, 0.7083],
         [0.7531, 1.0974, 0.9372, 0.1354, 0.9966],
         [0.9275, 2.8941, 0.8380, 0.5086, 0.6772],
         [0.3163, 0.8477, 0.0714, 1.1886, 0.8082]]])

In [9]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

a.resize_(6, 10)

torch.matmul(a, a.T, out=torch.Tensor(6, 6))

tensor([[3.0699, 1.3969, 2.3838, 1.6563, 1.9404, 2.3233],
        [1.3969, 2.2335, 2.2748, 0.7783, 1.4423, 1.8358],
        [2.3838, 2.2748, 3.8359, 1.8333, 2.7232, 2.5390],
        [1.6563, 0.7783, 1.8333, 1.3199, 1.4468, 1.3470],
        [1.9404, 1.4423, 2.7232, 1.4468, 2.7060, 2.2397],
        [2.3233, 1.8358, 2.5390, 1.3470, 2.2397, 3.2353]])

In [10]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = torch.tensor(1., requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2., requires_grad=True)

y = (x ** 3) + z - 75 * t

y.backward()

x.grad, z.grad, t.grad

(tensor(3.), tensor(1.), tensor(-75.))

In [11]:
# Создайте единичный тензор размера 5x6

ones = torch.ones(5, 6)

ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [12]:
# Переведите его в формат numpy

ones.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [13]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

In [14]:
from torch import nn
from torch import optim
from torch.autograd import Variable

In [15]:
x_data = Variable(torch.tensor([[1.0]]))
y_data = Variable(torch.tensor([[2.0]]))
w1 = Variable(torch.randn(1), requires_grad=True)

In [16]:
def forward(x):
    y = x ** w1 - 2 * x ** 2 + 5
    return y

In [17]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD([w1], lr=0.001)

In [18]:
optimizer.zero_grad()
y_pred = forward(x_data)
loss = criterion(y_pred, y_data)
print('loss: ', loss.item())
print ('dY/dw1: ', w1.grad) 

loss:  4.0
dY/dw1:  None


In [19]:
loss.backward()
print ('dY/dw1: ', w1.grad)
print ('w1: ', w1)

dY/dw1:  tensor([0.])
w1:  tensor([1.5451], requires_grad=True)


In [20]:
optimizer.step()
print ('w1: ', w1)
print ('y_pred: ', x_data ** w1 - 2 * x_data ** 2 + 5)

w1:  tensor([1.5451], requires_grad=True)
y_pred:  tensor([[4.]], grad_fn=<AddBackward0>)
